version: "3"
services:
   web:
     image: nginx
     ports:
       - "80:80"
     volumes:
       - ./dist:/usr/share/nginx/html
       - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
       - ./nginx/conf.d:/etc/nginx/conf.d
       - ./nginx/logs:/var/log/nginx
     restart: always
     container_name: p0001clientdaily